### ISSUE TITLE
SYSTEM_FRESH_OUT_OF_RESET flag not cleared after initialization; may cause sensor crash on board reboot

### ISSUE THREAD

**Issue by pramilo** [adafruit/Adafruit_VL6180X#15] opened 2019-12-22 19:10 UTC
During the initialization sequence of the sensor, you check the VL6180X_SYSTEM_FRESH_OUT_OF_RESET bit:

`readByte(VL6180X_ADDRESS, VL6180X_SYSTEM_FRESH_OUT_OF_RESET)`

If it's 1, you then proceed to initializing the registers.

The problem is that you don't set it to 0 after you initialize the registers.
The Application Note AN4545 suggests that it is teh user who needs to do this by actively writing a 0 to the register.
The Application Note also recommends this to be done so that user code can know it has already initialized them.

Not setting the register to 0 causes problems in a particular scenario:
- Board boots and runs sensor initialization code.
- Sensor is set to some form of continuous sampling (Range, for example) during initialization
- Board is rebooted (by uploading a new sketch, for example). Power was not cycled and therefore, the sensor was NOT power cycled.
- Once the board boots, because the VL6180X_SYSTEM_FRESH_OUT_OF_RESET flag was not cleared by writing the 0 to it, the function `readByte(VL6180X_ADDRESS, VL6180X_SYSTEM_FRESH_OUT_OF_RESET)` will return 1 once again
- Code will attempt to write and manipulate configuration registers while sampling may be progress (assuming we set the sensor for continuous sampling)
- This appears to crash the sensor. Only a power cycle of both board and sensor seems to recover them.

The correct behavior would be to place the following instruction at the end of the register initialization sequence:
`writeByte(VL6180X_ADDRESS, VL6180X_SYSTEM_FRESH_OUT_OF_RESET, 0);`

Suggest this is added to the initialization sequence. If this is done, upon a board reboot, it won't attempt to reconfigure registers while running continuous sampling, because the test  `readByte(VL6180X_ADDRESS, VL6180X_SYSTEM_FRESH_OUT_OF_RESET)` wold then return 0.

Thank you

**Comment by ladyada** [comment] 2019-12-22 19:22
if you try changing it, see if it works same/better and submit a PR :)

**Comment by SimetriNick** [comment] 2021-08-04 19:34
Has this been fixed?

**Comment by SimetriNick** [comment] 2021-08-04 21:11
> Has this been fixed?

No it has not;  I have tried pramilo's proposed fix, and was still having an issue where the sensor would crash / stop reading and only a power cycle would fix it. 

I'm still doing testing to confirm, but the problem I had is that I was starting the continuous read, and was not always stopping it. So even though  VL6180X_SYSTEM_FRESH_OUT_OF_RESET was correctly being checked and reset, sometimes VL6180X_REG_SYSRANGE_START was still set to ON (0x03) and then the loadsettings() call would crash the sensor. 

I propose that before calling loadsettings, we check to see if continuous read is turned on, and if it is, we turn it off to manipulate configuration registers, and then turn it back on after that has been completed. 

I am clocking out for the day, but I will attempt this fix and create a pull request first thing tomorrow, as per ladyada's request ! :)

**Comment by caternuson** [comment] 2021-08-04 21:25
What is a simple example sketch that can be used to demonstrate this issue?

**Comment by SimetriNick** [comment] 2021-08-05 14:24
> What is a simple example sketch that can be used to demonstrate this issue?
 
I haven't had time to dig deeper into this to replicate / make the proposed fix yet; My best guess at replicating this would be to follow the Adafruit_VL6180X triple example, strip everything but continuous ranging, and play with where/when the start and stop functions are called.  Try starting it, and not stopping it, then resetting / power cycling and note the behavior. 
 
 To be honest I'm not 100% sure what the root of my specific problem was, but I do know that the only things I changed to fix the issue were :
 - I uncommented lines 67 and 69 in the library cpp (this is the if statmente checking the reset register)
 - Stopped using continuous reading altogether, and switched to single shot ranging. I also added a call to stopRangeContinuous() in the setup, to ensure it is off.

**Comment by pramilo** [comment] 2021-08-05 15:14
I made the original post and it seems I should add some context into this, and why this matters:

The point of clearing this flag is so that, when your code runs, so that you can differentiate: 
- if you're coming from a hard Power Up (meaning the Sensor is at its default configuration per the datasheet)
- or the processor is restarting but there wasn't actually a Power cycle. This happens, for example, when you program an Arduino, where the processor resets but your main voltage rail might not.

This is ESSENTIAL to know because the sensor is very picky (i.e. crashes) if receiving initialization commands when it's already running-

For example, if you're coming from a hard reset, you might set up the registers and start _continuous ranging mode_.
If you run the same set of initialization instructions but the sensor was already initialized and running (i.e. your processor restarted but the sensor was not reset), then the sensor crashes or has unexpected behavior.

Therefore, the point of this flag - first and foremost is to clear it on boot - but besides that, is to have you write two code paths: one for initializing the sensor on first boot and a different one if the sensor is already initialized.

This seems quite logical to me.

_I'd like to emphasize: the point here is beyond clearing the FRESH OUT OF RESET flag; it is to let you know the state of the sensor._

I made a quick search in the datasheet and on google to see if there is a way to make a SOFT RESET and couldn't find any obvious one. 
So really, if the sensor is _not fresh out of reset_, then you should avoid re-running initialization code on a sensor that's already up and running. 
This is why FRESH OF RESET matters and why I opened this issue.

I have since written my own code for my application (moved on from this library) so I can't say much about the library itself; can only say about operating the sensor.

**Comment by caternuson** [comment] 2021-08-05 16:21
Looks like the value is currently set to 0. But the conditional checks are commented out. Not sure why that is. Wonder if this could be fixed by just uncommenting those? (and maybe moving the 0 set inside the conditional)
https://github.com/adafruit/Adafruit_VL6180X/blob/7bc5dd32e2a774861af812213019172086ad8088/Adafruit_VL6180X.cpp#L65-L69

**Comment by caternuson** [comment] 2021-08-05 17:28
@SimetriNick are you able to test if that fixes things?

**Comment by SimetriNick** [comment] 2021-08-05 18:57
> @SimetriNick are you able to test if that fixes things?

Just uncommenting those conditional checks did not fix the issue for me, I ended up switching to single shot ranging and added a call to stop continuous ranging in the setup. 

I'm still not sure what was making the sensor crash, but I am almost positive its related to the continuous ranging  register and/or the reset register. 

The behavior I was seeing in my code was that the sensor would crash immediately after starting up or being flashed, causing a domino affect of bugs, but hitting the reset button made everything work as expected.

**Comment by caternuson** [comment] 2021-08-05 19:09
OK, thanks for trying. So seems like there may be more going on.

**Comment by SimetriNick** [comment] 2021-08-18 19:10
We're still having issues related to this, but it appears the SPARKFUN library for this sensor does not have this issue; basically our sensor gives us inconsistent readings, and random "RAW READING UNDERFLOW" Errors, one thing we've found to fix it is to flash the board with the adafruit example, then flash it again with our code, and the sensor readings work well / are consistent again, until the power is cycled. 

I bet this has something to do with how the registers are set, as the Sparkfun library initializes differently, with more register write calls.

**Comment by caternuson** [comment] 2021-08-18 23:03
Do you have an example sketch (preferably as simple as possible) that works with the Sparkfun library but does not work with the Adafruit library?

**Comment by pramilo** [comment] 2021-08-19 16:42
> We're still having issues related to this, but it appears the SPARKFUN library for this sensor does not have this issue; basically our sensor gives us inconsistent readings, and random "RAW READING UNDERFLOW" Errors, one thing we've found to fix it is to flash the board with the adafruit example, then flash it again with our code, and the sensor readings work well / are consistent again, until the power is cycled.
> 
> I bet this has something to do with how the registers are set, as the Sparkfun library initializes differently, with more register write calls.

I'd suggest looking at the Application Note for the sensor (page 5 and then section 9). It has a section that specifically describes how to properly initialize the registers.
There are also some proper diagrams explaining how to use the different ranging modes.

The latest one from ST is here https://www.st.com/resource/en/datasheet/vl6180.pdf but there also seems to be an older one from 2014 on the Sparkfun website.

IMHO experimenting with flashing different pieces of third party code is not really useful in terms of coming to a working setup; it'd be best looking at the documentation.

Furthermore most of these libraries from generic vendors never see the kind of demanding testing and debugging you'd need for a commercial application so relying on them without fully understanding the code may not be very wise.

**Comment by caternuson** [comment] 2021-08-24 22:52
@pramilo Which app note?
> I'd suggest looking at the Application Note for the sensor (page 5 and then section 9).

This one? [AN4545 VL6180X basic ranging application note ](https://www.st.com/resource/en/application_note/an4545-vl6180x-basic-ranging-application-note-stmicroelectronics.pdf)

**Comment by caternuson** [comment] 2021-08-25 14:55
Going to close this. The issue is unclear and can not be recreated. Some concerns brought up in initial post are also untrue. AN4545 (and datasheet) were referenced when writing the library, see various code comments throughout. With PR #24 the fresh_out_of_memory check has been put back in, fwiw. This is called "optional" in AN4545. The AN4545 suggested initialization was already in place (see `loadSettings`). So hopefully the concerns raised in initial post have been covered.

If some one can come up with a simple sketch that can reliably and repeatably demonstrate the issue, we can reopen this and continue investigating.

**Closed as completed by caternuson** 2021-08-25 14:55 UTC
